"""
-----------
Dijkstra's single-source shortest-path algorithm, implemented from
scratch using ``heapq`` as a binary-heap priority queue.

This is Algorithm A in the EnergyPath comparison. It requires all
edge weights to be non-negative -- a requirement that holds for the
EnergyPath domain (mental-energy costs are always >= 0) and for every
benchmark graph generated by ``graph_generator.generate_random_graph``.

Complexity (proved in README.md, Section "Complexity Analysis"):
    Time:  O((V + E) log V)   with a binary heap
    Space: O(V + E)
"""

from __future__ import annotations

import heapq
import time
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

AdjacencyList = Dict[int, List[Tuple[int, float]]]

INF = float("inf")


@dataclass
class DijkstraResult:
    """Container for everything the UI / benchmark code needs."""

    distance: float                 # total cost, INF if unreachable
    path: List[int]                  # node ids, source ... target (empty if unreachable)
    runtime_seconds: float            # wall-clock time for the search only
    visited_count: int                 # nodes popped from the heap (diagnostic)


def dijkstra(
    adj: AdjacencyList,
    source: int,
    target: Optional[int] = None,
) -> DijkstraResult:
    """Run Dijkstra's algorithm from ``source``.

    Args:
        adj: adjacency list, ``adj[u] = [(v, weight), ...]``. All
            weights must be non-negative.
        source: starting vertex id.
        target: if given, the search still computes full single-source
            distances (no early-exit shortcut is taken) so that
            runtime comparisons against Bellman-Ford -- which always
            computes all distances -- remain apples-to-apples. The
            path is then reconstructed only for this target.

    Returns:
        DijkstraResult with distance, path, runtime, and a visited
        counter for diagnostics.

    Raises:
        ValueError: if any edge weight is negative (Dijkstra's
            correctness proof, see README.md, assumes non-negative
            weights; the function checks this defensively).
    """
    for u, neighbors in adj.items():
        for _, w in neighbors:
            if w < 0:
                raise ValueError(
                    f"Dijkstra requires non-negative weights; found edge "
                    f"from node {u} with weight {w}. Use Bellman-Ford instead."
                )

    start_time = time.perf_counter()

    dist: Dict[int, float] = {node: INF for node in adj}
    prev: Dict[int, Optional[int]] = {node: None for node in adj}
    dist[source] = 0.0

    # Min-heap of (distance, node). A "lazy deletion" approach is used:
    # stale entries are skipped via the `visited` set rather than
    # decreasing keys in place (heapq has no decrease-key operation).
    heap: List[Tuple[float, int]] = [(0.0, source)]
    visited: set = set()
    visited_count = 0

    while heap:
        d, u = heapq.heappop(heap)
        if u in visited:
            continue
        visited.add(u)
        visited_count += 1

        for v, weight in adj.get(u, []):
            if v in visited:
                continue
            new_dist = d + weight
            if new_dist < dist[v]:
                dist[v] = new_dist
                prev[v] = u
                heapq.heappush(heap, (new_dist, v))

    runtime = time.perf_counter() - start_time

    path: List[int] = []
    if target is not None and dist.get(target, INF) < INF:
        path = _reconstruct_path(prev, source, target)

    return DijkstraResult(
        distance=dist.get(target, INF) if target is not None else 0.0,
        path=path,
        runtime_seconds=runtime,
        visited_count=visited_count,
    )


def dijkstra_all_distances(adj: AdjacencyList, source: int) -> Tuple[Dict[int, float], float]:
    """Convenience wrapper used by the benchmark suite: returns the
    full distance dictionary plus runtime, without requiring a target."""
    start_time = time.perf_counter()
    dist, _ = _dijkstra_raw(adj, source)
    runtime = time.perf_counter() - start_time
    return dist, runtime


def _dijkstra_raw(adj: AdjacencyList, source: int) -> Tuple[Dict[int, float], Dict[int, Optional[int]]]:
    """Internal helper: plain Dijkstra without timing/validation
    overhead, used when only the raw distance map is needed."""
    dist: Dict[int, float] = {node: INF for node in adj}
    prev: Dict[int, Optional[int]] = {node: None for node in adj}
    dist[source] = 0.0
    heap: List[Tuple[float, int]] = [(0.0, source)]
    visited: set = set()

    while heap:
        d, u = heapq.heappop(heap)
        if u in visited:
            continue
        visited.add(u)
        for v, weight in adj.get(u, []):
            if v in visited:
                continue
            new_dist = d + weight
            if new_dist < dist[v]:
                dist[v] = new_dist
                prev[v] = u
                heapq.heappush(heap, (new_dist, v))

    return dist, prev


def _reconstruct_path(prev: Dict[int, Optional[int]], source: int, target: int) -> List[int]:
    """Walk the predecessor map backwards from target to source."""
    path = [target]
    node = target
    while node != source:
        node = prev[node]
        if node is None:
            return []  # unreachable
        path.append(node)
    path.reverse()
    return path
